### ISSUE TITLE
Documentation: Separate README.md for each example

### ISSUE THREAD

**Issue by nhrones** [Hexagon/pup#1]
It's not clear how to run the example.
How about a small readme.md in the example folder?

**Comment by Hexagon** [comment]
Thanks for the feedback! 👍 

A README.md in each example folder would be great. With a short note on how to run (eather install globally before running `pup` in the example folder, or run `deno run ../../pup.ts`). Also, each readme could have a section describing the options used in the example and why.

**Comment by devharsh007** [comment]
If you could elaborate me  that what  things to add. I would like to do it.

**Comment by Hexagon** [comment]
👍 

Just a quick summary on what each example do and how to run it. Similar to the docker example. You can use that and the running instructions at https://github.com/Hexagon/pup#examples as a template
