### ISSUE TITLE
Command not found error

### ISSUE THREAD

**Issue by tiborsaas** [Hexagon/pup#28]
Hello,

I've installed Pup on a Ubuntu instance, but I get the following error:

```
root@webapp:~# deno install -Afr https://deno.land/x/pup/pup.ts
Warning Implicitly using latest version (1.0.0-beta.26) for https://deno.land/x/pup/pup.ts
✅ Successfully installed pup
/root/.deno/bin/pup
ℹ️  Add /root/.deno/bin to PATH
    export PATH="/root/.deno/bin:$PATH"
root@webapp:~# pup
Command 'pup' not found, but there are 16 similar ones.
```

I get this after restarting the terminal.

I'm using Ubuntu: 
```
Release:        22.10
Codename:       kinetic
```

**Comment by Hexagon** [comment]
Not sure why, but as the putput states, you have to run 

`export PATH="/root/.deno/bin:$PATH"`

... or add it to you shell rc/profile and login/logout

To get the deno/bin path added to PATH

**Comment by Hexagon** [comment]
Not much to do about this, it's already documented too - https://hexagon.github.io/pup/installation.html#installing-or-upgrading-pup

Reopen if you have any suggestions.
