### ISSUE TITLE
Fails to autostart on reboot on Debian

### ISSUE THREAD

**Issue by martin-braun** [Hexagon/pup#43]
It's very unstable. I also have the problem that the service will not properly activate on reboot. `systemd --user` also hangs, something is off.

```json
{
  "processes": [
    {
      "id": "cronmon",
      "cmd": "deno run --ext=ts --unstable --allow-read --allow-net --import-map=deno.json --lock=lock.json cronmon.ts",
      "autostart": true
    }
  ]
}
```

is my pup.json. `pup status` says nothing is running. `systemd --user` hangs, so I can only `<C-c>`. After installing the service things worked only partially, the service was active, but Deno wasn't really running, sounds like the issue #21, but this is Debian. I uninstalled the service and re-installed carefully. Then `systemctl --user daemon-reload` even reported `Failed to connect to bus: No such file or directory`.

What seems to work though is uninstalling the service before reboot and re-installing the service after reboot.

**Comment by martin-braun** [comment]
Sample project with the issue: https://github.com/martin-braun/cronmon

**Comment by Hexagon** [comment]
Very interesting! When having it started, check what `pup logs` and `systemctl --user status cronmon` says. Make sure to run all commands from the same directory as your pup.json resides.

**Comment by Hexagon** [comment]
Also check `systemctl --version` `pup --version` and `deno --version`

**Comment by martin-braun** [comment]
@Hexagon I tried to replicate, now it's working. Maybe the issue was on me. Also `systemctl` sometimes take a while to start, I think that might was the culprit. I will keep an eye on it, if I face issues again, I will re-open. Thanks for the nice ecosystem tool.
