### ISSUE TITLE
Documentation: Json schema for pup.json

### ISSUE THREAD

**Issue by nhrones** [Hexagon/pup#5]

**Comment by nhrones** [comment]
Would be nice to have a json $schema for pup,json.

**Comment by Hexagon** [comment]
Agree, work started in

https://github.com/Hexagon/pup/blob/main/tools/build-schema.ts with upstream issue https://github.com/StefanTerdell/zod-to-json-schema/issues/47

**Comment by Hexagon** [comment]
We can keep this open as a reminder 👍

**Comment by Hexagon** [comment]
Available in `docs/pup.schema.json` from `1.0.0-alpha-6`
