### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by nhrones** [Hexagon/pup#6]
lib/core/pup.ts
Error lines, 55, 59 - Property 'name' does not exist on type 'ProcessConfiguration'.deno-ts(2339)

**Comment by Hexagon** [comment]
It sounds like you use an old version or something, have you installed - which version are you running? (pup --version) or do you run directly from the repo?

**Comment by nhrones** [comment]
Pup is moving way to fast for me to keep up!
I'll give it a while to settle in.

**Comment by Hexagon** [comment]
😄  It's just a couple of days old, so the details are still forming. But it should start to settle soon, keep the feedback flowing!
